#!/usr/bin/env python3
"""Generate v7 - from _gen_backtest.py with D3 momentum fork added"""
import os
L = []
def a(s): L.append(s)

a('"""D1D2回测v7 — 跟踪止盈 + D3动量分叉 + 仓位权重"""')
a('import sys,os,json,warnings,time')
a("warnings.filterwarnings('ignore')")
a("sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))")
a('import pandas as pd,numpy as np')
a('from datetime import datetime')
a('from concurrent.futures import ThreadPoolExecutor,as_completed')
a('import sqlite3')
a('from config import DB_PATH')
a('')
a('TRAIL_PCT=3.0; TRAIL_WIDE=5.0; MAX_HOLD=5')
a('')
a('def get_sl_tp(d1_chg):')
a('    if d1_chg>=10: return 0.93,1.07')
a('    elif d1_chg>=8: return 0.95,1.05')
a('    elif d1_chg>=6: return 0.97,1.04')
a('    else: return 0.98,1.03')
a('')
a('def calc_wt(d1_chg,pb):')
a('    if d1_chg>=8 and 3<=pb<5: return 2.5')
a('    if d1_chg>=8: return 1.5')
a('    if d1_chg>=6 and 3<=pb<5: return 1.5')
a('    if pb<2: return 0.5')
a('    return 1.0')
a('')
a('def check_pattern(code):')
a('    trades=[]')
a('    try:')
a('        conn=sqlite3.connect(DB_PATH)')
a("        df=pd.read_sql_query('SELECT * FROM daily_data WHERE code=? ORDER BY date',conn,params=(code,)); conn.close()")
a('        if df.empty or len(df)<60: return trades')
a("        for c in ['open','close','high','low','volume']: df[c]=pd.to_numeric(df[c],errors='coerce')")
a("        df=df.dropna(subset=['open','close','high','low','volume'])")
a('        idx=2')
a('        while idx<len(df):')
a('            try:')
a("                d1=df.iloc[idx-1]; d2=df.iloc[idx]")
a("                d1_chg=(d1['close']/d1['open']-1)*100")
a("                if d1_chg>=5 and d1['close']>d1['open']:")
a('                    lookback=min(20,idx)')
a("                    avg_vol=df.iloc[idx-1-lookback:idx-1]['volume'].mean()")
a("                    vr=d1['volume']/avg_vol if avg_vol>0 else 2")
a("                    dr=d1['high']-d1['low']")
a("                    cp=(d1['close']-d1['low'])/dr if dr>0 else 0.5")
a("                    dc_=float(d1['close']); do_=float(d1['open'])")
a('                    if vr>=1.3 and cp>=0.6:')
a("                        pb=(dc_-float(d2['close']))/dc_*100")
a("                        if 1.0<=pb<=8 and float(d2['close'])>float(d2['open']):")
a("                            bp=max(float(d2['low'])*1.003,do_*0.97)")
a('                            sp,tp_=get_sl_tp(d1_chg)')
a('                            sl=bp*sp; tp=bp*tp_')
a('                            tr=False; pk=bp')
a('                            ex=None; h=0; r=""')
a('                            d3p=False; tpt=TRAIL_PCT')
a('                            for hold in range(1,MAX_HOLD+1):')
a('                                ei=idx+hold')
a('                                if ei>=len(df): break')
a('                                dy=df.iloc[ei]')
a("                                dh=float(dy['high']); dl=float(dy['low']); dc2=float(dy['close'])")
a('                                if dl<=sl: ex=max(dl,sl); h=hold; r="止损"; break')
a('                                if tr:')
a('                                    pk=max(pk,dh)')
a('                                    sa=pk*(1-tpt/100)')
a('                                    if dl<=sa: ex=max(dl,sa); h=hold; r="跟踪止盈"; break')
a('                                else:')
a('                                    if dh>=tp: tr=True; pk=dh')
a('                                # D3动量分叉')
a('                                if hold==2 and not d3p:')
a('                                    d3p=True')
a("                                    do2=float(dy['open'])")
a('                                    if dc2<=do2: ex=dc2; h=hold; r="D3转弱"; break')
a('                                    else: tpt=TRAIL_WIDE')
a('                                if hold==MAX_HOLD: ex=dc2; h=hold; r="强卖"')
a('                            if ex is not None:')
a('                                pnl=(ex/bp-1)*100')
a('                                trades.append({')
a("                                    'code':code,")
a("                                    'd1_date':str(d1['date'])[:10],")
a("                                    'entry_date':str(d2['date'])[:10],")
a("                                    'buy_price':round(bp,2),")
a("                                    'exit_date':str(dy['date'])[:10],")
a("                                    'exit_price':round(ex,2),")
a("                                    'pnl_pct':round(pnl,2),")
a("                                    'hold_days':h,'is_win':pnl>0,")
a("                                    'd1_chg':round(d1_chg,1),")
a("                                    'd2_pullback':round(pb,1),")
a("                                    'exit_reason':r,")
a("                                    'weight':calc_wt(d1_chg,pb),")
a('                                })')
a('            except: pass')
a('            idx+=1')
a('    except: pass')
a('    return trades')
a('')
a('def get_cached_codes():')
a('    conn=sqlite3.connect(DB_PATH)')
a("    rows=conn.execute('SELECT code,COUNT(*) as cnt FROM daily_data GROUP BY code HAVING cnt>=60').fetchall(); conn.close()")
a("    return sorted([r[0] for r in rows if r[0].startswith(('0','3','6'))")
a("                    and not r[0].startswith(('300','301','688','689','8','4'))])")
a('')
a('def print_results(at,label=""):')
a('    if not at: print("no trades"); return')
a('    df=pd.DataFrame(at); wins=df[df["is_win"]]; n=len(df); nw=len(wins)')
a('    print(); print("="*60); print(f"{label}  {n}笔"); print("="*60)')
a("    wr=nw/n*100; mp=df['pnl_pct'].mean(); md=df['pnl_pct'].median()")
a("    print(f'胜率: {wr:.1f}% ({nw}/{n})  均: {mp:+.2f}%  中位: {md:+.2f}%')")
a("    mw=wins['pnl_pct'].mean(); ml=df[~df['is_win']]['pnl_pct'].mean()")
a("    print(f'盈利均: {mw:+.2f}%  亏损均: {ml:+.2f}%')")
a("    wa=(df['pnl_pct']*df['weight']).sum()/df['weight'].sum()")
a("    print(f'加权均: {wa:+.2f}%')")
a('    for e in ["跟踪止盈","止损","D3转弱","强卖"]:')
a("        sub=df[df['exit_reason']==e]")
a('        if sub.empty: continue')
a("        sw=sub[sub['is_win']]['is_win'].sum()/len(sub)*100")
a("        sm=sub['pnl_pct'].mean(); sh=sub['hold_days'].mean()")
a("        print(f'[{e}] {len(sub)}笔 {sw:.1f}% {sm:+.2f}% {sh:.1f}天')")
a("    for t in [5,6,8,10]:")
a("        sub=df[df['d1_chg']>=t]")
a('        if sub.empty: continue')
a("        print(f'D1>={t}%: {len(sub)}笔 {sub['is_win'].mean()*100:.1f}% {sub['pnl_pct'].mean():+.2f}%')")
a("    for lo,hi in [(1,2),(2,3),(3,5),(5,8)]:")
a("        sub=df[(df['d2_pullback']>=lo)&(df['d2_pullback']<hi)]")
a('        if sub.empty: continue')
a("        print(f'D2 {lo}-{hi}%: {len(sub)}笔 {sub['is_win'].mean()*100:.1f}% {sub['pnl_pct'].mean():+.2f}%')")
a("    for h in range(1,MAX_HOLD+1):")
a("        sub=df[df['hold_days']==h]")
a('        if sub.empty: continue')
a("        print(f'hold {h}d: {len(sub)}笔 {sub['is_win'].mean()*100:.1f}% {sub['pnl_pct'].mean():+.2f}%')")
a('')
a("if __name__=='__main__':")
a('    t0=time.time()')
a("    print(f'D1D2 v7 D3分叉 trail={TRAIL_PCT}/{TRAIL_WIDE}%')")
a("    print(datetime.now().strftime('%Y-%m-%d %H:%M'))")
a('    codes=get_cached_codes(); print(f"cache: {len(codes)}")')
a('    at=[]; done=0')
a('    with ThreadPoolExecutor(max_workers=20) as ex:')
a('        futures={ex.submit(check_pattern,c):c for c in codes}')
a('        for f in as_completed(futures):')
a('            done+=1')
a('            try: r=f.result()')
a('            except: r=None')
a('            if r: at.extend(r)')
a('            if done%500==0: print(f"[{done}/{len(codes)}] {len(at)} {time.time()-t0:.0f}s")')
a('    print(f"done {len(codes)} {len(at)}trades {time.time()-t0:.0f}s")')
a("    print_results(at,f'v7 D3分叉')")
a('    out=os.path.join(os.path.dirname(os.path.abspath(__file__)),"backtest_d1d2_v7_results.json")')
a('    with open(out,"w") as f: json.dump(at,f,ensure_ascii=False,indent=2)')
a('    print(f"saved {out}")')

out = r'C:\Users\Administrator\Desktop\quant_pulse\backtest\backtest_d1d2_v7.py'
with open(out, 'w', encoding='utf-8') as f:
    f.write('\n'.join(L))
print(f'Wrote {len(L)} lines to {out}')
